### ISSUE TITLE
[FR] Calibrate E Steps

### ISSUE THREAD

**Issue by gtr33m** [le3tspeak/Marlin-2.0.X-MKS-Robin-Nano#28] opened 2020-06-28 00:24 UTC
### Description

I would like to have a "Tuning" menu item added to the main menu, with the submenu item:
* Calibrate E-Steps

### Feature Workflow

1. Press Green button
2. Press Down to new menu item
3. Press Green button
4. Select function

Perform E Steps Calibration:
1. Loop to preheat menu so user can select material
1. Screen displays "Measure and mark 120mm of filament", Wait for OK
2. send the command G1 E100 F100
3. Screen displays "Extruding 100mm of filament"
4. Screen displays "Measure distance to mark"
5. Allow user input from 0.0mm to 40mm
6. Read current E steps value from EEPROM
7. Calculate new E Steps value using formula: ([current E]*100)/(120-[user value])
8. Send command M92 E[new E steps value]
9. screen displays "E Steps tune complete"

#### Additional Information

Might be good to add a M500 command after each or prompt the user to save.

**Comment by thierryzoller** [comment] 2020-06-28 09:59
There is already a PID Autotune inbuilt ?

**Comment by gtr33m** [comment] 2020-06-28 10:14
> There is already a PID Autotune inbuilt ?

Yes, just no menu item to access it.

**Comment by thierryzoller** [comment] 2020-06-28 10:19
It is enabled and there is a menu in the latest build.

Here is the config file, search to "PID" : https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/blob/MKS-Robin-Nano/Marlin/Configuration.h

**Comment by thierryzoller** [comment] 2020-06-28 10:20
Partially duplicate of #25

**Comment by gtr33m** [comment] 2020-06-28 10:24
> It is enabled and there is a menu in the latest build.
> 
> Here is the config file, search for "PID" : https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/blob/MKS-Robin-Nano/Marlin/Configuration.h

Not in the menu as of 1.0.6 builds?

**Comment by thierryzoller** [comment] 2020-06-28 10:29
The menu is not intuitive to find - https://upam.uni.lu/content/download/3045/14922/file/LCD%20Menu%20Tree.pdf

**Comment by gtr33m** [comment] 2020-06-28 10:34
> The menu is not intuitive to find - https://upam.uni.lu/content/download/3045/14922/file/LCD%20Menu%20Tree.pdf

 #define PID_AUTOTUNE_MENU     // Add PID auto-tuning to the "Advanced Settings" menu. (~250 bytes of PROGMEM)

But it's not in my menu under Advanced Settings or any of the sub menus.

**Comment by thierryzoller** [comment] 2020-06-28 10:39
You don't have the latest version then:
https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/compare/1.0.6...MKS-Robin-Nano

**Comment by gtr33m** [comment] 2020-06-28 10:45
> You don't have the latest version then:
> [1.0.6...MKS-Robin-Nano](https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/compare/1.0.6...MKS-Robin-Nano)

![image](https://user-images.githubusercontent.com/2274965/85945290-5cf09300-b96f-11ea-8f6c-f7701941c6a5.png)
![image](https://user-images.githubusercontent.com/2274965/85945295-6aa61880-b96f-11ea-8422-143d11cfacd3.png)
![image](https://user-images.githubusercontent.com/2274965/85945298-71349000-b96f-11ea-9f72-991f2b639045.png)
![image](https://user-images.githubusercontent.com/2274965/85945301-7f82ac00-b96f-11ea-9f67-f2f4549847f1.png)

But... this is in the middle of a print, so I'll have to double check when it's done.

**Comment by thierryzoller** [comment] 2020-06-28 11:07
PID Tuning is not accessible in the middle of a print ;)

**Comment by gtr33m** [comment] 2020-06-28 13:26
Checked after print and reboot. Menu is no different from above. Definitively not there. Checked configuration, advanced and temperature.

**Comment by le3tspeak** [comment] 2020-06-28 13:56
Is not activated in the release build 1.0.6 if you want it you have to build the firmware with the source code with VS code.

https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/compare/1.0.6...MKS-Robin-Nano

**Closed by le3tspeak** 2020-06-28 13:56 UTC
